from __future__ import annotations

import re
from collections import deque

import psycopg2
from psycopg2.extras import RealDictCursor
from sqlalchemy.engine import make_url

from app.core.config import settings


APP_STORE_SCHEMA = "app_store"
_INSERT_RE = re.compile(r"^\s*INSERT\s+INTO\s+([A-Za-z_][A-Za-z0-9_]*)", re.IGNORECASE)


class AppStoreOperationalError(Exception):
    pass


class AppStoreCursor:
    def __init__(self, cursor):
        self._cursor = cursor
        self._buffer = deque()
        self.lastrowid = None

    def execute(self, query: str, params=None):
        sql = query.replace("?", "%s")
        insert_match = _INSERT_RE.match(sql)
        appended_returning = False

        if insert_match and "returning" not in sql.lower():
            sql = sql.rstrip().rstrip(";") + " RETURNING id"
            appended_returning = True

        try:
            self._cursor.execute(sql, params or [])
        except psycopg2.Error as exc:
            raise AppStoreOperationalError(str(exc)) from exc

        if appended_returning:
            row = self._cursor.fetchone()
            if row is not None:
                self.lastrowid = row.get("id")
                self._buffer.append(row)

        return self

    def fetchone(self):
        if self._buffer:
            return self._buffer.popleft()
        return self._cursor.fetchone()

    def fetchall(self):
        rows = list(self._buffer)
        self._buffer.clear()
        rows.extend(self._cursor.fetchall())
        return rows

    @property
    def rowcount(self):
        return self._cursor.rowcount

    def close(self):
        self._cursor.close()


class AppStoreConnection:
    def __init__(self, connection):
        self._connection = connection

    def cursor(self):
        return AppStoreCursor(self._connection.cursor(cursor_factory=RealDictCursor))

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()


def _connect():
    url = make_url(settings.APP_DB_URL)
    connection = psycopg2.connect(
        host=url.host,
        port=url.port or 5432,
        dbname=url.database,
        user=url.username,
        password=url.password,
        options=f"-c search_path={APP_STORE_SCHEMA},public",
    )
    connection.autocommit = False
    return connection


def get_app_store_conn():
    return AppStoreConnection(_connect())


def _column_exists(cursor, table_name: str, column_name: str) -> bool:
    cursor.execute(
        """
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = %s
          AND table_name = %s
          AND column_name = %s
        """,
        (APP_STORE_SCHEMA, table_name, column_name),
    )
    return cursor.fetchone() is not None


def init_app_store():
    conn = get_app_store_conn()
    cur = conn.cursor()

    cur.execute(f"CREATE SCHEMA IF NOT EXISTS {APP_STORE_SCHEMA}")

    cur.execute("""
        CREATE TABLE IF NOT EXISTS recipes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            connection_id INTEGER,
            database_name TEXT,
            schema_name TEXT,
            object_name TEXT,
            recipe_name TEXT,
            user_prompt TEXT,
            statement_type TEXT,
            selected_tables_json TEXT,
            sql_text TEXT,
            explanation TEXT,
            created_at TEXT
        )
    """)

    cur.execute("""
        CREATE TABLE IF NOT EXISTS prompt_history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            connection_id INTEGER,
            database_name TEXT,
            schema_name TEXT,
            object_name TEXT,
            user_prompt TEXT,
            statement_type TEXT,
            sql_text TEXT,
            created_at TEXT
        )
    """)

    cur.execute("""
        CREATE TABLE IF NOT EXISTS connections (
            id INTEGER PRIMARY KEY,
            name TEXT,
            db_type TEXT,
            host TEXT,
            port TEXT,
            database_name TEXT,
            schema_name TEXT,
            username TEXT,
            password TEXT,
            account TEXT,
            warehouse TEXT,
            role TEXT,
            is_active BOOLEAN DEFAULT TRUE
        )
    """)

    cur.execute("""
        CREATE TABLE IF NOT EXISTS pipelines (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            description TEXT,
            connection_id INTEGER NOT NULL,
            database_name TEXT,
            schema_name TEXT,
            source_object TEXT,
            target_object TEXT,
            mapping_config TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
    """)

    cur.execute("""
        CREATE TABLE IF NOT EXISTS pipeline_steps (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            pipeline_id BIGINT NOT NULL REFERENCES pipelines(id) ON DELETE CASCADE,
            step_order INTEGER NOT NULL,
            step_name TEXT NOT NULL,
            step_type TEXT NOT NULL DEFAULT 'sql',
            sql_text TEXT NOT NULL,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
    """)

    cur.execute("""
        CREATE TABLE IF NOT EXISTS pipeline_runs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            pipeline_id BIGINT NOT NULL REFERENCES pipelines(id) ON DELETE CASCADE,
            status TEXT NOT NULL DEFAULT 'PENDING',
            trigger_type TEXT NOT NULL DEFAULT 'MANUAL',
            started_at TEXT NOT NULL,
            ended_at TEXT,
            duration_seconds DOUBLE PRECISION,
            total_steps INTEGER NOT NULL DEFAULT 0,
            success_steps INTEGER NOT NULL DEFAULT 0,
            failed_steps INTEGER NOT NULL DEFAULT 0,
            error_message TEXT,
            initiated_by TEXT,
            run_log TEXT
        )
    """)

    cur.execute("""
        CREATE TABLE IF NOT EXISTS pipeline_run_steps (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            pipeline_run_id BIGINT NOT NULL REFERENCES pipeline_runs(id) ON DELETE CASCADE,
            pipeline_id BIGINT NOT NULL REFERENCES pipelines(id) ON DELETE CASCADE,
            step_id BIGINT NOT NULL REFERENCES pipeline_steps(id) ON DELETE CASCADE,
            step_order INTEGER NOT NULL,
            step_name TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'PENDING',
            execution_order INTEGER DEFAULT 0,
            started_at TEXT,
            ended_at TEXT,
            duration_seconds DOUBLE PRECISION,
            executed_sql TEXT,
            rows_affected INTEGER DEFAULT 0,
            error_message TEXT,
            step_log TEXT
        )
    """)

    cur.execute("""
        CREATE TABLE IF NOT EXISTS pipeline_schedules (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            pipeline_id BIGINT NOT NULL UNIQUE REFERENCES pipelines(id) ON DELETE CASCADE,
            schedule_type TEXT NOT NULL DEFAULT 'interval',
            cron_expression TEXT,
            interval_minutes INTEGER,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            last_run_at TEXT,
            next_run_at TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
    """)

    for table_name, column_name, column_def in [
        ("pipelines", "mapping_config", "TEXT"),
        ("pipeline_runs", "trigger_type", "TEXT NOT NULL DEFAULT 'MANUAL'"),
        ("pipeline_runs", "duration_seconds", "DOUBLE PRECISION"),
        ("pipeline_runs", "error_message", "TEXT"),
        ("pipeline_runs", "initiated_by", "TEXT"),
        ("pipeline_run_steps", "execution_order", "INTEGER DEFAULT 0"),
        ("pipeline_run_steps", "duration_seconds", "DOUBLE PRECISION"),
        ("pipeline_run_steps", "executed_sql", "TEXT"),
    ]:
        if not _column_exists(cur, table_name, column_name):
            cur.execute(f"ALTER TABLE {table_name} ADD COLUMN {column_name} {column_def}")

    conn.commit()
    conn.close()